### ISSUE TITLE
Several errors at different steps

### ISSUE THREAD

**Issue by rfm-targa** [JackAidley/PhasomeIt#1]
Greetings,

Thank you for thinking about a program like this and developing it. It accomplishes something important that I'm interested in and I'm looking forward to use it if you can help me with some problems.

I've followed all recommendations and attempted to run the program with the .gbk files used in your study, from [Campylobacter](https://figshare.com/articles/Host_specified_Campylobacter_genomes/7066487).

First, it raised an exception because in the _phasomeit.py_ script, line 154 it would pass a full directory as argument and, apparently, it should be a string with the name of a file? The line is:

`plugins = [SpeciesAnnotator(args.target, settings.metadataCsv)]`

As I understand it will give _args.target_, that is a directory as an argument that corresponds to a filename and that will raise an exception in the speciesannotator.py script, line 10 when the _open_ function detects that the string is a directory. The line in _speciesannotator.py_ is:

`with open(csvFilename, newline='') as csvFile:`

I tried to change the line 158 in _phasomeit.py_ to:

`plugins = [SpeciesAnnotator(args.target.split('/')[-1], settings.metadataCsv)]`

In order to pass only the last word of the directory as the filename and it passed that point, but another exception was raised in the _polygfinder.py_ script, line 211, where the program attempts to determine the length of a _NoneType_ object and raises an exception. The line is:

`if filter != None:`

Is this because I did not define the filter argument?
I changed it to:

```
if filter != None:
    if len(filter) > 0:
```

To avoid the exception and work properly. After that, I executed the program with the Campylobacter .gbk files and it worked fine for 126 files but not for the rest.

Could you verify this situations? I would appreciate it very much if you could correct anything that is wrong or if I'm missing anything about how to execute the program. The command I used after altering the code was:

`python3.6 phasomeit.py -t full_directory -c 5`

Thanks in advance,

Rafael

**Comment by JackAidley** [comment]
Hi Rafael,

Apologies for the error, I'd somehow managed to check in a hybrid version which had conflicting changes between phasomeit.py and speciesannotator.py which resulted in the directory crash bug. I have now checked in a fixed version.

When you try and run the I suspect that a cutoff of 5 for single nucleotide repeats will cause the program to grind to a shuddering halt as there are simply too many of them. We usually use cutoff parameters of "-c 7 6 10 5 5 -f w9" for Campylobacter which includes poly-G/C tracts of length 7 or more, and poly-A/T of 9 or more. Although there are the single nucleotide tracts are, by far, the most important in Campylobacter. If you work with other species, your paramters will need to be tuned to the particular bacteria you work with depending on what SSRs are responsible for variation.

I hope you find the software useful and please feel free to contact me if you have any further problems.

Cheers,

Jack.

**Comment by rfm-targa** [comment]
Greetings,

Thank you so much for your response in such a short time. I've tried to run the program but I got an error related with the filter argument:

`File "/home/user/testDir/PhasomeIt-master/polygfinder.py", line 211, in findAllPolysInStrain
    if len(filter) > 0 :
TypeError: object of type 'NoneType' has no len()`

I am not providing any value for the filter argument because the code and the documentation seem to indicate that it is not obligatory, right? Should I always define a value for the filter argument? Right now it seems it won't execute properly without providing a value for the filter argument because it will try to verify the length of the argument and not defining a value leads to a NoneType object and an exception.

Much appreciated,

Rafael

**Comment by JackAidley** [comment]
Hi Rafael,

No, it shouldn't be requiring a filter, but I think I've always run it with one, so I guess that slipped through. I will see if I can fix that. In the meantime, you can simply set a filter with the argument '-f w1' and it will have no effect.

Cheers,

Jack.

**Comment by JackAidley** [comment]
Okay, that turned out to be super-easy to fix, and a fix is now live.

**Comment by rfm-targa** [comment]
Hey there,

Everything is executing fine and I'm getting the output files without any error or warning. Thank you so much! I'll start looking at the results. Wouldn't be this easy without PhasomeIt. Thank you for the support.

All the best,

Rafael
