### ISSUE TITLE
Error execution

### ISSUE THREAD

**Issue by ireneortega** [JackAidley/PhasomeIt#2]
Hi Jack!

I'm very interested in using Phasomeit, but I'm having troubles. I can't run Phasomeit due to a directory problem I don't know how to solve. This is the command I'm running:

```
irene@irene-VirtualBox:~/PhasomeIt_v1_1_1/PhasomeIt$ python3 phasomeit.py -t ./NCTC11168 -c 0 --firstSpecies jejuni --firstStrains NCTC11168
Traceback (most recent call last):
  File "phasomeit.py", line 171, in <module>
    main()
  File "phasomeit.py", line 154, in main
    plugins = [SpeciesAnnotator(args.target, settings.metadataCsv)]
  File "/home/irene/PhasomeIt_v1_1_1/PhasomeIt/speciesannotator.py", line 10, in __init__
    with open(csvFilename, newline='') as csvFile:
IsADirectoryError: [Errno 21] Is a directory: './NCTC11168'
```

And you can check that NCTC11168 exists with NCTC11168.gbk inside:

```
irene@irene-VirtualBox:~/PhasomeIt_v1_1_1/PhasomeIt$ ls
blastmatch.py        findpvinstrains.py  loghandler.py   resources
bossref              genegroups.py       NCTC11168       settings.py
Bossref.exe          genomecrawler.py    phasomeit.py    speciesannotator.py
copyfastas.py        genomefetcher.py    polyCounter.py  Versions.txt
featurefinder.py     htmlify.py          polygfinder.py
findassociations.py  html.py             __pycache__
```

```
irene@irene-VirtualBox:~/PhasomeIt_v1_1_1/PhasomeIt$ cd ./NCTC11168; ls
NCTC11168.gbk  _phasomeit.log
```

Could you please help me? Thanks!! 

Irene

**Comment by JackAidley** [comment]
Dear Irene,

I actually fixed this bug about a year and a half ago in the code on GitHub but I neglected to update the latest release .zip to include the code change. You can now download it from [here](https://github.com/JackAidley/PhasomeIt/releases/tag/v1.1.2) and it should fix your problem. Sorry for the inconvenience.

However, I also note that you appear to only have a single genome in your dataset and I am not sure that PhasomeIt will function correctly in this case as the code was designed for comparing multiple genomes.

All the best,

Jack.

**Comment by ireneortega** [comment]
Many thanks Jack! 

However, it seems Phasomeit is not working properly as this error appears now after BLAST is completed (with 37 strains tested):

```
Reading BLASTsTraceback (most recent call last):
  File "phasomeit.py", line 172, in <module>
    main()
  File "phasomeit.py", line 156, in main
    findpvinstrains.findPVinFolder(args.target, args.filter, args.cutoffs, plugins)
  File "/home/irene/PhasomeIt_v1_1_2/PhasomeIt/findpvinstrains.py", line 94, in findPVinFolder
    blastmatch.blastComparePVs(db, targetPath)
  File "/home/irene/PhasomeIt_v1_1_2/PhasomeIt/blastmatch.py", line 407, in blastComparePVs
    readBlast(db, path, strain)
  File "/home/irene/PhasomeIt_v1_1_2/PhasomeIt/blastmatch.py", line 173, in readBlast
    for record in NCBIXML.parse(outHandle) :
  File "/home/irene/.local/lib/python3.6/site-packages/Bio/Blast/NCBIXML.py", line 798, in parse
    raise ValueError("Your XML file was empty")
ValueError: Your XML file was empty
```

Thanks for your help!

Irene

**Comment by ireneortega** [comment]
Hi Jack!

I definitely got it in Windows with `BLAST 2.10.1+` (adding variable system BLASTDB_LMDB_MAP_SIZE = 1000000 as commented here https://www.biostars.org/p/413294/), `Python 3.7.8`, `BioPython-1.77` and `Natsort-7.0.1`. I will try the execution in Linux as we are insterested in using PhasomeIt in that system. Now, we're discussing how to handle with the data, so any advice is welcome. 
Thanks!

Irene

**Comment by Jonathan-Holmes-Bioinformatics** [comment]
Hi Jack, 

Just a quick note the Bio.Alphabet package has been removed from Bio Python sometime in the past 6 months. I'm in Chris's lab group and we've had a few people asking about programme not working. 
I believe I've resolved all issues with the following:

polygfinder.py
remove all instances of IUPAC.unambiguous_dna
findpvinstrains.py 
remove contig['record'].seq.alphabet from strip 

Do you mind letting me know if these fixes are correct and if so updating the github repository? 

Cheers,
Jonathan

**Comment by JackAidley** [comment]
Hi Irene and Jonathan,

I have now updated the code to version 1.1.3, which will work with the latest version of Python (3.9) and BioPython (1.78). 

Best regards,

Jack.
