### ISSUE TITLE
Question regarding "Filtering results"

### ISSUE THREAD

**Issue by maesaar** [JackAidley/PhasomeIt#3]
First of all thank you for the incredible program. I have one question regarding **Filtering results** where it is stated:

> **FILTERING RESULTS**
>With species with a low (or high) G/C content, chance is likely to skew the results, especially as A/T tracts are less variable and need to be longer to produce a phase variable effect. Filtering allows extraneous results to be removed. Currently only a single filter can be set for any run. Filters are specified as {repeat-unit}{maximum-length-to-ignore} (no space between the two) and repeat-unit types support the normal four DNA letters plus W and S, so - for example - adding '-f W9' would remove all A/T tracts of length 9 or less from the analysis (i.e. treat the minimum A/T length as 10). `A filter cutoff of 'W9' was used in our analysis`.

I have read the paper, but I did not find any references to filter cutoff W9, but the Phasomelt outputs from Figshare contain T/A length from 10 so W9 must have been applied.

Did I miss the reference to -f W9 in the manuscript?

Thank you!

**Comment by JackAidley** [comment]
Hi Maesaar,

Thank for your kind words. I don't think we give the exact command line parameters in the manuscript itself, but it is stated in the "Poly-G/C are the most common form of putatively variable tract in Campylobacter species" section that we used "Cut-offs for poly-G/C (≥7), poly-A/T (≥10), dinucleotide (≥6) and longer repeat units (≥5) were selected based on published data". The '-f W9' parameter produces this 'poly-A/T (≥10)' cutoff. In hindsight, probably it would have been more intuitive to specify this as '-f W10'.

**Comment by maesaar** [comment]
Thank you for the quick answer. It was my mistake somehow I missed the paragraph in the manuscript! Thank you for pointing it out to me.

Am I correct that when -f W then it means A/T and when -f S then it means G/C?

**Comment by JackAidley** [comment]
Yes, W and S are as per the IUPAC codes. I didn't add the other multibase codes as I don't believe they are ever needed.

**Comment by maesaar** [comment]
@JackAidley Thank you very much!
