### ISSUE TITLE
Bio.Alphapet error!

### ISSUE THREAD

**Issue by maesaar** [JackAidley/PhasomeIt#4]
While running PhasomeIt I get following error:
`ImportError: Bio.Alphabet has been removed from Biopython`

How to fix it?

**Comment by JackAidley** [comment]
Hi Maesaar,

Thanks for bringing this to my attention. Apparently this module was removed with the update of BioPython to 1.78. You will need to downgrade to a version of BioPython 1.77 or earlier, and use a version of Python 3.7 or earlier. I will try and get round to fixing PhasomeIt to be compatible with the latest versions of both shortly.

**Comment by maesaar** [comment]
Thank you!

**Comment by maesaar** [comment]
Now I have other error:

```
Traceback (most recent call last):
  File "phasomeit.py", line 172, in <module>
    main()
  File "phasomeit.py", line 146, in main
    t=time.clock()
AttributeError: module 'time' has no attribute 'clock'
```

**Comment by JackAidley** [comment]
This is because you are using Python 3.8 or later; you need to downgrade to Python 3.7 or earlier.

**Comment by maesaar** [comment]
Thanks again! Installed new conda environment with python 3.7, biopython 1.77, NatSort and blast. Everything works!
