### ISSUE TITLE
cj1024c (flgR) is not detected

### ISSUE THREAD

**Issue by ireneortega** [JackAidley/PhasomeIt#6]
I have found that cj1024c (flgR) containts several homopolymeric tracts (https://onlinelibrary.wiley.com/doi/abs/10.1111/j.1365-2958.2006.05336.x), however, PhasomeIt doesn't identify this gen as hipervariable. I used this options: `-c 7 6 10 5 5 -f W9` What could be the reason? 
In the data attached with your publication, neither is this gen detected.

**Comment by JackAidley** [comment]
The tracts identified as variable in that locus are poly-A/T tracts, shorter in length that the level where we usually set our cutoffs. It is possible to set PhasomeIt to identify poly-A/T tracts of that length by altering the cutoff values and removing the '-f W9' filter however you will find that poly-A/T tracts of that length are so common at that length that you the output produced will be nearly useless.

We also found in the Bayliss lab that poly-A/T tracts are significantly less variable than poly-G/C tracts and thus the tracts in that locus wouldn't meet our criteria for being hypervariable, and was one reason that I chose a cutoff of 7 for G/C tracts but 10 for A/T tracts. I can't remember whether that data ever got published though.
