### ISSUE TITLE
Output format

### ISSUE THREAD

**Issue by ireneortega** [JackAidley/PhasomeIt#9]
I am working with 130 genomes and the HTML output format is not very user-friendly for filtering PV tracts in all genomes. I am only interested in the ON/OFF state of the PV tracts (Table named as Tract lengths and ON/OFF by PV Gene groups
) of the O-linked glycosillation locus in Campylobacter. PV tract groups are not ordered regarding locustag of --firstStrains. Well, to some extent, yes, but when reaching final of --firstStrains genome, more locustag of this strain are shown that should be placed in upper rows. For example, 

...
NC.._01421 (last locustag with PV tract in genome)
NC.._00646
NC.._00029
...

should be shown in my opinion as 
...
NC.._00029
NC.._00646
NC.._01421 (last locustag with PV tract in genome)
...

This complicate the task of selecting the PV groups between the two genes delimiting that cluster, because that cluster is fragmented in various rows due to the disorder of locustag in --firstStrains, or maybe I am lossing genes of this cluster in other genomes that are not present in the --firstStrains.
Althoug I can copy that table to Excel and select specific rows, the blue and red colors are lost after copying it from the HTML file, and I can't analyse then the ON/OFF state because I don't have that information.

What can I do?

**Comment by JackAidley** [comment]
The ordering of the PV tracts won't be changed. It is behaving as intended, and changing it as an option would require more extensive work than I'm willing to do.

I don't know why Excel doesn't copy over the background values of the cells, but a workaround you can use for this is to copy and paste to Google Sheets instead and then use the download option to export that to an Excel worksheet. If that's not sufficient then I could alter that output page to also include text for whether a tract is in a putative On or Off state.

**Comment by ireneortega** [comment]
@JackAidley Awesome! I wish I had known it before. Now I can work in the results effectively. I would recommend you if you could indicate this in the README file of this repository to help other users.

Thanks a lot.
